import Head from 'next/head'
import React from 'react'

export default function Ichiran() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <>
                    {isEditable ? (
                        <div>
                            <input
                                type="text"
                                label="新しいタイトル"
                                value={newTitle}
                                onChange={handleEditFormChange}
                            />
                            <button onClick={handleEditTodo}>編集を保存</button>
                            <button onClick={handleCloseEditForm}>キャンセル</button>
                        </div>
                    ) : (
                        <div>
                            <input
                                type="text"
                                label="タイトル"
                                value={todoTitle}
                                onChange={handleAddFormChanges}
                            />
                            <button onClick={handleAddTodo}>作成</button>
                            <select value={filter} onChange={(e) => setFilter(e.target.value)}>
                                <option value="all">すべて</option>
                                <option value="notStarted">未着手</option>
                                <option value="inProgress">作業中</option>
                                <option value="done">完了</option>
                            </select>
                        </div>
                    )}

                    <ul>
                        {/* 問題3. 絞り込んだtodoを一覧に渡そう*/}
                        {filteredTodos.map((todo) => (
                            <li key={todo.id}>
                                <span>{todo.title}</span>
                                <select
                                    value={todo.status}
                                    onChange={(e) => handleStatusChange(todo, e)}
                                >
                                    <option value="notStarted">未着手</option>
                                    <option value="inProgress">作業中</option>
                                    <option value="done">完了</option>
                                </select>
                                <button onClick={() => handleOpenEditForm(todo)}>編集</button>
                                <button onClick={() => handleDeleteTodo(todo)}>削除</button>
                            </li>
                        ))}
                        {/* ここまで */}
                    </ul>
                </>
            </main>
        </>
    );
}


